version: '3.7'

services:
  stock:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    command: python manage.py makemigrations
    command: python manage.py migrate
    volumes:
      - .:/stock
    ports:
      - "8000:8000"