# Generated by Django 2.2.3 on 2019-07-23 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=18)),
                ('model', models.CharField(max_length=60)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('year', models.DecimalField(decimal_places=0, max_digits=5)),
                ('color', models.CharField(max_length=20)),
                ('seats', models.DecimalField(decimal_places=0, max_digits=2)),
                ('doors', models.DecimalField(decimal_places=0, max_digits=1)),
                ('gear_type', models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic'), ('SA', 'Semi-Automatic')], max_length=2)),
                ('config', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=11)),
                ('description', models.TextField(max_length=1024)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
