# Generated by Django 2.2.3 on 2019-07-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mileage',
            field=models.CharField(default='10000', help_text='E.g 128000, Specify mileage in kilometers', max_length=8),
        ),
    ]
