# Generated by Django 2.2.3 on 2019-07-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsell', '0002_auto_20190730_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_type',
            field=models.CharField(choices=[('compact', 'Compact'), ('convertible', 'Convertible'), ('coupe', 'Coupe'), ('off-road/pick-up', 'Off-Road/Pick-Up'), ('sedan', 'Sedan'), ('wagon', 'Wagon'), ('truck', 'Truck'), ('van', 'Van'), ('other', 'Other')], default='', max_length=16),
        ),
    ]
