# Generated by Django 2.2.3 on 2019-07-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsell', '0003_post_body_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='engine_type',
            field=models.CharField(default='', help_text='E.g Twin turbo V8 or V12', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='mileage',
            field=models.CharField(default='', help_text='E.g 128000, Specify mileage in kilometers', max_length=8),
        ),
    ]
