# Generated by Django 2.2.3 on 2019-07-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsell', '0004_auto_20190730_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_type',
            field=models.CharField(choices=[('compact', 'Compact'), ('convertible', 'Convertible'), ('coupe', 'Coupe'), ('crossover', 'Crossover'), ('pick-up', 'Pick-Up'), ('suv', 'SUV'), ('sedan', 'Sedan'), ('wagon', 'Wagon'), ('truck', 'Truck'), ('van', 'Van'), ('other', 'Other')], default='', max_length=16),
        ),
    ]
