# Generated by Django 2.2.3 on 2019-08-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsell', '0005_auto_20190730_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_post.jpg', upload_to='post_pics'),
        ),
    ]
